name: deploy

on:
  push:
    branches:
      - main
    paths:
      - nginx.conf
      - 'MaaAssistantArknights/**'
      - .github/workflows/deploy.yml
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Version Name
        id: version_name
        run: |
          version=$(date --utc +%Y%m%d%H%M%S)
          echo "version=$version" | tee -a "$GITHUB_OUTPUT"
          
          cd MaaAssistantArknights/api
          echo $version | jq -c '{timestamp:.}' | tee lastUpdateTime.json

      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: local
          mirrorchyan_rid: MaaResourceCache
          working-directory: "MaaAssistantArknights/api/"
          pick_files: '["gui", "resource", "lastUpdateTime.json"]'
          version_name: ${{ steps.version_name.outputs.version }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}

      - name: Setup ssh key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OTA_SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -H ${{ secrets.OTA_SERVER_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Sync repository
        run: |
          ssh ${{ secrets.OTA_SERVER_SSH_USER }}@${{ secrets.OTA_SERVER_SSH_HOST }} \
            "
              set -e
              mkdir -p ~/MaaRelease
              cd ~/MaaRelease
              git init
              git fetch --force --no-tags --prune --update-head-ok --progress  \
                'https://github.com/${{ github.repository }}' \
                '+HEAD:refs/remotes/origin/HEAD'
              git checkout --force --progress refs/remotes/origin/HEAD

              echo Generating lastUpdateTime.json
              mkdir -p MaaAssistantArknights/api/
              echo ${{ steps.version_name.outputs.version }} | jq -c '{timestamp:.}' | tee MaaAssistantArknights/api/lastUpdateTime.json
            "
