name: Generate stageAndTasksUpdateTime

on:
  push:
    branches:
      - main
    paths:
      - 'MaaAssistantArknights/api/gui/StageActivity.json'
      - 'MaaAssistantArknights/api/resource/**'
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Version Name
        id: version_name
        run: |
          version=$(date --utc +%Y%m%d%H%M%S)
          echo "version=$version" | tee -a "$GITHUB_OUTPUT"

      - name: Setup ssh key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OTA_SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -H ${{ secrets.OTA_SERVER_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Sync repository
        run: |
          ssh ${{ secrets.OTA_SERVER_SSH_USER }}@${{ secrets.OTA_SERVER_SSH_HOST }} \
            "
              set -e
              mkdir -p ~/MaaRelease
              cd ~/MaaRelease

              echo Generating json
              mkdir -p MaaAssistantArknights/api/
              echo ${{ steps.version_name.outputs.version }} | jq -c '{timestamp:.}' | tee MaaAssistantArknights/api/stageAndTasksUpdateTime.json
            "
